[log]
enabled = false

[net]
tickrate = 30
port = 1211
log_late_msg = false

[server]
id = "mining-devel"

[game]
hostname = "Mining Station 14 DEVEL"
lobbyenabled = true
role_timers = false
lobbyduration = 3
defaultpreset = "Mining"
min_players = 1
map_pool = "MiningMapPool"

[ic]
flavor_text = true

[console]
# If this is true, people connecting from this machine (loopback)
# will automatically be elevated to full admin privileges.
# This literally works by checking if address == 127.0.0.1 || address == ::1
loginlocal = true

[auth]
# Authentication (accounts):
# 0 = Optional, 1 = Required, 2 = Disabled
# Presumably do require authentication on any public server.
mode = 0

[atmos]
space_wind = true
space_wind_max_velocity = 25.0 # from default 30
superconduction = true

[vote]
enabled = true
map_enabled = false
preset_enabled = false
restart_enabled = true
timermap = 30

[ooc]
enable_during_round = true

[rules]
time = 0.0

[ghost]
role_time = 0.0

[adminlogs]
enabled = false

[events]
enabled = true

[rl]
endpoint = "http://localhost:7042"
